name: C:\Users\Juan\Documents\Projects\data-driven-web-apps-with-flask\ejercicio_TdeC
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - iapws=1.4.1
  - intel-openmp=2020.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - mkl=2020.0
  - numpy=1.18.1
  - openssl=1.1.1g
  - pip=20.1
  - python=3.8.2
  - python_abi=3.8
  - scipy=1.3.2
  - setuptools=46.1.3
  - sqlite=3.30.1
  - wheel=0.34.2


